"""initial schema

Revision ID: de1f58e5536c
Revises:
Create Date: 2026-07-26 16:55:43.802719

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "de1f58e5536c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "channel_launches",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("niche", sa.Text(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_channel_launches_status"), "channel_launches", ["status"], unique=False
    )
    op.create_table(
        "channels",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("channel_id", sa.String(length=64), nullable=False),
        sa.Column("refresh_token_encrypted", sa.Text(), nullable=False),
        sa.Column("access_token", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("workflow", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("inputs", sa.JSON(), nullable=False),
        sa.Column("states", sa.JSON(), nullable=False),
        sa.Column("events", sa.JSON(), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=False),
        sa.Column("error", sa.Text(), nullable=False),
        sa.Column("source_job_id", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_jobs_status"), "jobs", ["status"], unique=False)
    op.create_index(op.f("ix_jobs_workflow"), "jobs", ["workflow"], unique=False)
    op.create_table(
        "performance_records",
        sa.Column("video_id", sa.String(length=64), nullable=False),
        sa.Column("job_id", sa.String(length=32), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("measured_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("video_id"),
    )
    op.create_index(
        op.f("ix_performance_records_measured_at"),
        "performance_records",
        ["measured_at"],
        unique=False,
    )
    op.create_table(
        "quota_entries",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("operation", sa.String(length=64), nullable=False),
        sa.Column("cost", sa.Integer(), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("channel_id", sa.String(length=64), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_quota_entries_at"), "quota_entries", ["at"], unique=False)
    op.create_index(
        "ix_quota_entries_at_operation", "quota_entries", ["at", "operation"], unique=False
    )
    op.create_table(
        "schedule",
        sa.Column("video_id", sa.String(length=64), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("job_id", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("video_id"),
    )
    op.create_index(op.f("ix_schedule_at"), "schedule", ["at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_schedule_at"), table_name="schedule")
    op.drop_table("schedule")
    op.drop_index("ix_quota_entries_at_operation", table_name="quota_entries")
    op.drop_index(op.f("ix_quota_entries_at"), table_name="quota_entries")
    op.drop_table("quota_entries")
    op.drop_index(op.f("ix_performance_records_measured_at"), table_name="performance_records")
    op.drop_table("performance_records")
    op.drop_index(op.f("ix_jobs_workflow"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_status"), table_name="jobs")
    op.drop_table("jobs")
    op.drop_table("channels")
    op.drop_index(op.f("ix_channel_launches_status"), table_name="channel_launches")
    op.drop_table("channel_launches")
    # ### end Alembic commands ###
