"""Verify TLS against the certificates *this machine* trusts.

Python does not use the operating system's certificate store. It uses `certifi`,
a fixed bundle of public roots compiled into the package. That is the right
default on a server and the wrong one on a laptop, because of one very common
situation:

Consumer antivirus with HTTPS scanning switched on — AVG, Avast, Kaspersky,
ESET, Bitdefender, and most corporate proxies and VPNs — terminates every TLS
connection, inspects it, and re-signs it with a root certificate it installs
into the Windows store. Browsers read that store, so the web keeps working.
Python reads certifi, which has never heard of it, so *every* outbound call
fails:

    ConnectError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed:
    unable to get local issuer certificate

This is what it looks like from the outside, and why it is so hard to place: the
Google OAuth callback returns Internal Server Error, keyword research reports
"no keyword evidence", Pexels returns nothing, and the voiceover stage dies at
the ninth of seventeen stages — four unrelated-looking bugs, none of which
mentions certificates, on a machine whose browser reaches all four services
perfectly well. It was diagnosed here from a root named "AVG Web/Mail Shield
Root, generated by AVG Antivirus for SSL/TLS scanning".

`truststore` fixes it at the source: it makes `ssl.SSLContext` defer to the
platform verifier (SChannel on Windows, Security.framework on macOS, OpenSSL
against the system store on Linux). Everything that builds a context afterwards
— httpx, and therefore every provider in this repo — inherits it. It is the same
mechanism pip switched to for the same reason.

Nothing is weakened. The platform verifier is stricter than certifi in most
respects, and it is the same one the browser already used to decide the
connection was fine. Disabling verification is the tempting shortcut here, and
would hand every API key on the machine to anything on the path.

Two things this deliberately does not do:

- **It does not fail.** A missing or broken `truststore` leaves certifi in place,
  which is exactly the behaviour that shipped before this module existed.
- **It does not replace `SSL_CERT_FILE`.** That variable still works, and is
  still what `workflows/media.py` reads to reach inside edge-tts. Somewhere with
  a bundle already exported by hand keeps working; this only means most people
  never have to.
"""

from __future__ import annotations

from loguru import logger

#: What happened, for `diagnostics.py` to report. Set once, by `install()`.
STATUS: str = "not attempted"

_installed = False


def install() -> str:
    """Point Python's TLS verification at the OS trust store. Safe to call twice.

    Called from `engine/__init__.py` rather than from application startup,
    because it has to happen before anything builds an `ssl.SSLContext` — and
    `edge_tts` builds one at module import time, as a module-level global it
    then passes explicitly to every connection. Importing the engine at all is
    the only seam reliably earlier than that.
    """
    global STATUS, _installed
    if _installed:
        return STATUS

    try:
        import truststore
    except ImportError:
        # Reachable on an environment installed before truststore was added to
        # pyproject.toml, which is every existing checkout until it is re-run.
        STATUS = "truststore is not installed - using certifi's bundle"
        logger.debug(STATUS)
        _installed = True
        return STATUS

    try:
        truststore.inject_into_ssl()
    except Exception as exc:  # noqa: BLE001 - never let this stop the engine booting
        STATUS = f"could not use the system trust store ({type(exc).__name__}) - using certifi"
        logger.warning(STATUS)
    else:
        STATUS = "using the system certificate store"
        logger.debug(STATUS)

    _installed = True
    return STATUS
